In [4]:
import pandas as pd
import json

### Criação das variáveis com os dados que serão trabalhados

In [ ]:
vendas_jan2025 = pd.read_csv('vendas_jan2025.csv', sep=';', encoding='latin-1')

with open('catalogo_produtos.json', 'r') as f:
    json_bruto = json.load(f)
catalogo_produtos = pd.json_normalize(json_bruto, sep='_')

lojas_nordeste = pd.read_excel('lojas_nordeste.xlsx', sheet_name='ativas')

In [20]:
vendas_jan2025.info()

<class 'pandas.DataFrame'>
RangeIndex: 160 entries, 0 to 159
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_transacao         160 non-null    int64
 1   data_venda           160 non-null    str
 2   id_loja              160 non-null    int64
 3   id_produto           160 non-null    int64
 4   quantidade           160 non-null    int64
 5   preco_unitario       160 non-null    str
 6   desconto_percentual  148 non-null    str
 7   vendedor             143 non-null    str
 8   forma_pagamento      138 non-null    str
dtypes: int64(4), str(5)
memory usage: 11.4 KB

In [23]:
vendas_jan2025['data_venda']

0      17/01/2025
1      07/01/2025
2      09/01/2025
3      04/01/2025
4      23/01/2025
          ...
155    2025-01-13
156    27/01/2025
157    29/01/2025
158    2025-01-10
159    2025-01-16
Name: data_venda, Length: 160, dtype: str

In [26]:
datas_iso_hifen = pd.to_datetime(vendas_jan2025['data_venda'], format='%Y-%m-%d', errors='coerce')

In [27]:
datas_iso_hifen

0            NaT
1            NaT
2            NaT
3            NaT
4            NaT
         ...
155   2025-01-13
156          NaT
157          NaT
158   2025-01-10
159   2025-01-16
Name: data_venda, Length: 160, dtype: datetime64[us]

In [32]:
datas_iso_hifen.unique()

<DatetimeArray>
[                'NaT', '2025-01-19 00:00:00', '2025-01-12 00:00:00',
 '2025-01-25 00:00:00', '2025-01-08 00:00:00', '2025-01-23 00:00:00',
 '2025-01-31 00:00:00', '2025-01-15 00:00:00', '2025-01-16 00:00:00',
 '2025-01-13 00:00:00', '2025-01-24 00:00:00', '2025-01-05 00:00:00',
 '2025-01-07 00:00:00', '2025-01-28 00:00:00', '2025-01-29 00:00:00',
 '2025-01-26 00:00:00', '2025-01-21 00:00:00', '2025-01-03 00:00:00',
 '2025-01-02 00:00:00', '2025-01-27 00:00:00', '2025-01-06 00:00:00',
 '2025-01-14 00:00:00', '2025-01-09 00:00:00', '2025-01-20 00:00:00',
 '2025-01-30 00:00:00', '2025-01-01 00:00:00', '2025-01-17 00:00:00',
 '2025-01-04 00:00:00', '2025-01-10 00:00:00']
Length: 29, dtype: datetime64[us]

In [33]:
datas_br = pd.to_datetime(vendas_jan2025['data_venda'], format='%d/%m/%Y', errors='coerce')

In [35]:
datas_br.unique()

<DatetimeArray>
['2025-01-17 00:00:00', '2025-01-07 00:00:00', '2025-01-09 00:00:00',
 '2025-01-04 00:00:00', '2025-01-23 00:00:00', '2025-01-11 00:00:00',
                 'NaT', '2025-01-12 00:00:00', '2025-01-10 00:00:00',
 '2025-01-03 00:00:00', '2025-01-27 00:00:00', '2025-01-01 00:00:00',
 '2025-01-30 00:00:00', '2025-01-20 00:00:00', '2025-01-28 00:00:00',
 '2025-01-02 00:00:00', '2025-01-22 00:00:00', '2025-01-26 00:00:00',
 '2025-01-15 00:00:00', '2025-01-29 00:00:00', '2025-01-31 00:00:00',
 '2025-01-25 00:00:00', '2025-01-13 00:00:00', '2025-01-08 00:00:00',
 '2025-01-06 00:00:00', '2025-01-24 00:00:00', '2025-01-16 00:00:00',
 '2025-01-14 00:00:00']
Length: 28, dtype: datetime64[us]

In [39]:
vendas_jan2025['data_venda'] = datas_iso.fillna(datas_br)

In [41]:
vendas_jan2025.info()

<class 'pandas.DataFrame'>
RangeIndex: 160 entries, 0 to 159
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_transacao         160 non-null    int64
 1   data_venda           160 non-null    datetime64[us]
 2   id_loja              160 non-null    int64
 3   id_produto           160 non-null    int64
 4   quantidade           160 non-null    int64
 5   preco_unitario       160 non-null    str
 6   desconto_percentual  148 non-null    str
 7   vendedor             143 non-null    str
 8   forma_pagamento      138 non-null    str
dtypes: datetime64[us](1), int64(4), str(4)
memory usage: 11.4 KB

In [42]:
vendas_jan2025

,id_transacao,data_venda,id_loja,id_produto,quantidade,preco_unitario,desconto_percentual,vendedor,forma_pagamento
0,5092,2025-01-17,104,1004,42,"R$ 41,65","10,7%",Carlos Souza,Cartão Crédito
1,5047,2025-01-07,105,1010,32,"R$ 63,70","17,9%",Ana Silva,Dinheiro
2,5129,2025-01-09,102,1007,32,"R$ 53,90","11,8%",Fernanda Costa,Cartão Crédito
3,5104,2025-01-04,102,1008,6,"R$ 64,52","24,5%",João Pereira,Cartão Débito
4,5099,2025-01-23,102,1004,44,"R$ 12,24","19,1%",ana silva,NaN
...,...,...,...,...,...,...,...,...,...
155,5085,2025-01-13,102,1014,32,"R$ 68,51","19,5%",João Pereira,Dinheiro
156,5052,2025-01-27,101,1002,27,"R$ 27,87","12,2%",Carlos Souza,NaN
157,5069,2025-01-29,102,1010,13,"R$ 74,91","21,0%",ana silva,Dinheiro
158,5036,2025-01-10,102,1008,23,"R$ 12,21","8,9%",ana silva,Dinheiro
159,5130,2025-01-16,105,1004,48,"R$ 86,63","12,1%",Ana Silva,NaN

In [49]:
vendas_jan2025['preco_unitario'] = (vendas_jan2025['preco_unitario']
 .str.replace(r'R\$ ', '', regex=True)
 .str.replace(',', '.')
 .str.strip()
 .astype('float') 
)

In [50]:
vendas_jan2025.info()

<class 'pandas.DataFrame'>
RangeIndex: 160 entries, 0 to 159
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_transacao         160 non-null    int64
 1   data_venda           160 non-null    datetime64[us]
 2   id_loja              160 non-null    int64
 3   id_produto           160 non-null    int64
 4   quantidade           160 non-null    int64
 5   preco_unitario       160 non-null    float64
 6   desconto_percentual  148 non-null    str
 7   vendedor             143 non-null    str
 8   forma_pagamento      138 non-null    str
dtypes: datetime64[us](1), float64(1), int64(4), str(3)
memory usage: 11.4 KB

In [51]:
vendas_jan2025

,id_transacao,data_venda,id_loja,id_produto,quantidade,preco_unitario,desconto_percentual,vendedor,forma_pagamento
0,5092,2025-01-17,104,1004,42,41.65,"10,7%",Carlos Souza,Cartão Crédito
1,5047,2025-01-07,105,1010,32,63.70,"17,9%",Ana Silva,Dinheiro
2,5129,2025-01-09,102,1007,32,53.90,"11,8%",Fernanda Costa,Cartão Crédito
3,5104,2025-01-04,102,1008,6,64.52,"24,5%",João Pereira,Cartão Débito
4,5099,2025-01-23,102,1004,44,12.24,"19,1%",ana silva,NaN
...,...,...,...,...,...,...,...,...,...
155,5085,2025-01-13,102,1014,32,68.51,"19,5%",João Pereira,Dinheiro
156,5052,2025-01-27,101,1002,27,27.87,"12,2%",Carlos Souza,NaN
157,5069,2025-01-29,102,1010,13,74.91,"21,0%",ana silva,Dinheiro
158,5036,2025-01-10,102,1008,23,12.21,"8,9%",ana silva,Dinheiro
159,5130,2025-01-16,105,1004,48,86.63,"12,1%",Ana Silva,NaN

In [59]:
vendas_jan2025['desconto_percentual'] = (vendas_jan2025['desconto_percentual']
 .str.replace(',', '.')
 .str.replace(r'\%', '', regex=True)
 .str.strip()
 .astype(float)
) / 100

In [60]:
vendas_jan2025.info()

<class 'pandas.DataFrame'>
RangeIndex: 160 entries, 0 to 159
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_transacao         160 non-null    int64
 1   data_venda           160 non-null    datetime64[us]
 2   id_loja              160 non-null    int64
 3   id_produto           160 non-null    int64
 4   quantidade           160 non-null    int64
 5   preco_unitario       160 non-null    float64
 6   desconto_percentual  148 non-null    float64
 7   vendedor             143 non-null    str
 8   forma_pagamento      138 non-null    str
dtypes: datetime64[us](1), float64(2), int64(4), str(2)
memory usage: 11.4 KB

In [68]:
index_nulos = (vendas_jan2025['desconto_percentual'].isna() == True)

In [70]:
vendas_jan2025.loc[index_nulos]

,id_transacao,data_venda,id_loja,id_produto,quantidade,preco_unitario,desconto_percentual,vendedor,forma_pagamento
16,5017,2025-01-30,105,1010,17,77.50,NaN,João Pereira,Cartão Crédito
30,5101,2025-01-30,103,1006,5,64.06,NaN,ana silva,Boleto
45,5123,2025-01-28,101,1001,9,43.99,NaN,Carlos Souza,Cartão Crédito
46,5116,2025-01-07,101,1011,17,70.65,NaN,Carlos Souza,Dinheiro
54,5011,2025-01-21,102,1012,5,56.71,NaN,Ana Silva,Dinheiro
56,5026,2025-01-02,105,1015,37,37.04,NaN,Fernanda Costa,NaN
61,5068,2025-01-07,105,1002,24,47.15,NaN,MARIA LIMA,PIX
66,5065,2025-01-09,105,1015,26,68.69,NaN,MARIA LIMA,Boleto
83,5038,2025-01-15,102,1003,3,11.66,NaN,Maria Lima,Cartão Crédito
100,5054,2025-01-28,101,1010,2,68.35,NaN,Carlos Souza,Cartão Crédito
105,5084,2025-01-30,102,1010,2,61.61,NaN,Carlos Souza,Dinheiro
132,5002,2025-01-15,103,1012,27,77.41,NaN,Ana Silva,Cartão Débito

In [74]:
index_nulos_vendedor = (vendas_jan2025['vendedor'].isna() == True)

In [75]:
vendas_jan2025.loc[index_nulos_vendedor]

,id_transacao,data_venda,id_loja,id_produto,quantidade,preco_unitario,desconto_percentual,vendedor,forma_pagamento
13,5126,2025-01-01,105,1005,1,13.65,0.055,NaN,NaN
25,5106,2025-01-31,102,1001,32,10.83,0.138,NaN,Dinheiro
29,5066,2025-01-26,105,1012,35,12.41,0.193,NaN,Cartão Crédito
34,5122,2025-01-10,102,1009,23,4.48,0.091,NaN,Cartão Crédito
52,5027,2025-01-15,104,1008,24,59.08,0.207,NaN,Dinheiro
70,5035,2025-01-26,101,1001,32,9.49,0.110,NaN,PIX
71,5049,2025-01-24,101,1007,22,79.31,0.134,NaN,PIX
75,5079,2025-01-20,104,1007,12,53.05,0.116,NaN,NaN
92,5032,2025-01-30,102,1001,35,86.55,0.171,NaN,Cartão Débito
94,5064,2025-01-14,103,1011,42,68.38,0.198,NaN,Cartão Crédito
111,5062,2025-01-03,105,1007,39,77.67,0.182,NaN,Cartão Débito
120,5138,2025-01-29,104,1007,22,7.23,0.017,NaN,PIX
125,5124,2025-01-16,104,1005,12,8.36,0.086,NaN,Cartão Débito
135,5023,2025-01-04,101,1015,6,54.11,0.248,NaN,PIX
141,5143,2025-01-14,105,1015,16,51.35,0.158,NaN,Dinheiro
143,5028,2025-01-12,105,1014,29,43.09,0.200,NaN,Dinheiro
149,5141,2025-01-29,103,1003,12,89.29,0.066,NaN,Cartão Crédito

In [78]:
index_nulos_forma_pagamento = (vendas_jan2025['forma_pagamento'].isna() == True)

In [79]:
vendas_jan2025.loc[index_nulos_forma_pagamento]

,id_transacao,data_venda,id_loja,id_produto,quantidade,preco_unitario,desconto_percentual,vendedor,forma_pagamento
4,5099,2025-01-23,102,1004,44,12.24,0.191,ana silva,NaN
13,5126,2025-01-01,105,1005,1,13.65,0.055,NaN,NaN
15,5052,2025-01-27,101,1002,27,27.87,0.122,Carlos Souza,NaN
26,5042,2025-01-15,101,1015,31,76.50,0.220,Ana Silva,NaN
31,5145,2025-01-08,105,1005,22,48.70,0.101,João Pereira,NaN
39,5016,2025-01-28,104,1014,49,46.97,0.171,João Pereira,NaN
43,5003,2025-01-29,104,1010,27,64.30,0.123,ana silva,NaN
51,5136,2025-01-03,103,1015,39,4.55,0.206,Carlos Souza,NaN
56,5026,2025-01-02,105,1015,37,37.04,NaN,Fernanda Costa,NaN
74,5147,2025-01-16,103,1008,14,63.61,0.240,Fernanda Costa,NaN
75,5079,2025-01-20,104,1007,12,53.05,0.116,NaN,NaN
79,5029,2025-01-15,105,1011,49,50.64,0.047,Carlos Souza,NaN
96,5046,2025-01-13,103,1014,24,13.71,0.036,Ana Silva,NaN
113,5001,2025-01-07,101,1002,8,7.02,0.229,João Pereira,NaN
119,5089,2025-01-10,102,1013,22,46.22,0.215,MARIA LIMA,NaN
126,5042,2025-01-15,101,1015,31,76.50,0.220,Ana Silva,NaN
127,5114,2025-01-19,102,1010,30,36.01,0.035,Carlos Souza,NaN
129,5012,2025-01-26,102,1010,48,58.37,0.233,Fernanda Costa,NaN
139,5074,2025-01-27,101,1009,1,81.73,0.152,Ana Silva,NaN
154,5012,2025-01-26,102,1010,48,58.37,0.233,Fernanda Costa,NaN
156,5052,2025-01-27,101,1002,27,27.87,0.122,Carlos Souza,NaN
159,5130,2025-01-16,105,1004,48,86.63,0.121,Ana Silva,NaN

In [80]:
catalogo_produtos

,id_produto,nome_produto,categoria,preco_custo,peso_kg,perecivel,fornecedor_nome,fornecedor_cnpj,fornecedor_estado
0,1001,Manga Tommy,Frutas in Natura,"R$ 16,37",3.20,True,AgriFruit Ltda,12.345.678/0001-90,CE
1,1002,Acerola,Frutas in Natura,"R$ 42,04",0.60,True,AgriFruit Ltda,12.345.678/0001-90,CE
2,1003,CajÃ¡,Frutas in Natura,"R$ 42,27",3.47,True,AgriFruit Ltda,12.345.678/0001-90,CE
3,1004,Goiaba Vermelha,Frutas in Natura,"R$ 4,45",1.57,True,AgriFruit Ltda,12.345.678/0001-90,CE
4,1005,Graviola,Frutas in Natura,"R$ 32,31",0.43,True,AgriFruit Ltda,12.345.678/0001-90,CE
5,1006,Polpa de AÃ§aÃ­,Polpas Congeladas,"R$ 26,82",1.79,True,Polpas do Norte S.A.,98.765.432/0001-10,PE
6,1007,Polpa de CupuaÃ§u,Polpas Congeladas,"R$ 28,51",0.32,True,Polpas do Norte S.A.,98.765.432/0001-10,PE
7,1008,Polpa de MaracujÃ¡,Polpas Congeladas,"R$ 39,41",4.87,True,Polpas do Norte S.A.,98.765.432/0001-10,PE
8,1009,Polpa de Caju,Polpas Congeladas,"R$ 43,65",3.77,True,Polpas do Norte S.A.,98.765.432/0001-10,PE
9,1010,Polpa de Manga,Polpas Congeladas,"R$ 7,16",3.82,True,Polpas do Norte S.A.,98.765.432/0001-10,PE
10,1011,Suco de Laranja,Sucos Concentrados,"R$ 2,57",0.21,False,NaturSucos ME,11.222.333/0001-44,BA
11,1012,Suco de Uva Integral,Sucos Concentrados,"R$ 15,58",2.49,False,NaturSucos ME,11.222.333/0001-44,BA
12,1013,Suco de Abacaxi,Sucos Concentrados,"R$ 35,01",3.45,False,NaturSucos ME,11.222.333/0001-44,BA
13,1014,Banana Chips,Frutas Desidratadas,"R$ 20,90",1.44,False,SecaFrut IndÃºstria,55.666.777/0001-88,PI
14,1015,Manga Desidratada,Frutas Desidratadas,"R$ 44,87",2.19,False,SecaFrut IndÃºstria,55.666.777/0001-88,PI
15,1003,CajÃ¡,Frutas in Natura,"R$ 8,50",1.20,True,AgriFruit Ltda,12.345.678/0001-90,CE

In [81]:
lojas_nordeste

,id_loja,nome_loja,cidade,estado,metros_quadrados,data_inauguracao,gerente
0,101,Frutally Fortaleza Centro,Fortaleza,CE,320.0,12/03/2019,Ricardo Mendes
1,102,Frutally Recife Boa Viagem,Recife,PE,280.0,2020-07-15,Patrícia Alves
2,103,Frutally Salvador Pituba,Salvador,BA,NaN,05/11/2021,Bruno Nascimento
3,104,Frutally Teresina Centro,Teresina,PI,195.0,2022-01-10,Luciana Rocha
4,105,Frutally São Luís,São Luís,MA,410.0,15/08/2023,Thiago Borges